#!/data/data/com.termux/files/usr/bin/bash

clear

echo $command 
echo "-----------------"
echo "1. Video to MP3"
echo "-----------------"

read option
read outputfilename

if [[ -z $option ]];
then
	clear
	printf "\e[031m Please choose a option!"
else
case $option in #Make Case list
	1)
	ffmpeg -i $command $outputfilename.avi
	;;
	2)
	echo " "
	;;
	
	3)
	break
	;;
esac 
fi
